# Generated by Django 4.0.4 on 2022-04-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramenta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='ferramenta',
        ),
    ]
